#' Function to do Bucher Method
#'
#' @param AB_IPD A data.frame of IPD from the AB trial. Generated by `gen_data()`.
#' @param AC_aggregate A data.frame of aggregate data from the AC trial. Generated
#' by `gen_data()`.
#'
#' @return A data.frame of bucher results, consisting of bucher_log_OR, bucher_se,
#' bucher_ci_lower, and bucher_ci_upper.
#'
#' @examples
#' # generate data
#' test_data <- gen_data()
#'
#' # do bucher
#' bucher(test_data$AB_IPD, test_data$AC_aggregate)
#'
#' @export

bucher <- function(AB_IPD, AC_aggregate) {
  # Estimated log OR of C vs. A
  d.AC.log <- with(AC_aggregate, log(y_C_sum * (N_A - y_A_sum) / (y_A_sum * (N_C - y_C_sum))))
  var.d.AC.log <- with(AC_aggregate, 1/y_A_sum + 1/(N_A - y_A_sum) + 1/y_C_sum + 1/(N_C - y_C_sum))

  # Estimated log OR of B vs. A
  AB_y_sum <- AB_IPD %>% dplyr::group_by(treatment) %>%
    dplyr::summarise(y_sum = sum(y)) %>%
    tidyr::pivot_wider(
      names_from = treatment,
      values_from = y_sum
    ) %>%
    as.data.frame()

  rownames(AB_y_sum) <- "y_sum"

  N <- nrow(AB_IPD)

  d.AB.AB.log <- log(AB_y_sum$B * (N / 2 - AB_y_sum$A) / (AB_y_sum$A * (N / 2 - AB_y_sum$B)))
  var.d.AB.AB.log <- 1 / AB_y_sum$B + 1/(N / 2 - AB_y_sum$A) + 1 / AB_y_sum$A + 1/(N / 2 - AB_y_sum$B)

  # Indirect comparison of C vs. B
  d.BC.Bucher.log <-  d.AC.log - d.AB.AB.log
  var.d.BC.Bucher.log <- var.d.AC.log + var.d.AB.AB.log

  # Confidence interval
  CI <- ci_from_x_and_se(d.BC.Bucher.log, sqrt(var.d.BC.Bucher.log))

  # Results
  results <-
    cbind(
      data.frame(
        bucher_log_OR = d.BC.Bucher.log,
        bucher_se = sqrt(var.d.BC.Bucher.log)),
      CI
    ) %>% dplyr::rename(
      bucher_ci_lower = ci_lower,
      bucher_ci_upper = ci_upper
    )

  rownames(results) <- NULL

  results
}

