#' Objective Function used in Weight Calculation
#'
#' This function calculates the sum of the exponentials of the matrix product of "X" and "a1"
#'
#' @param a1 A numeric vector.
#' @param X A numeric matrix.
#'
#' @return A numeric value representing the sum of the exponentials of the matrix product of "X" and "a1".
#'
#' @examples
#' a1 <- c(0.1, 0.2, 0.3)
#' X <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3)
#' objfn(a1, X)
#'
#' @noRd
objfn <- function(a1, X){
  sum(exp(X %*% a1))
}

#' Gradient Function used in Weight Calculation
#'
#' This function calculates the gradient of a given matrix "X" and a vector "a1".
#'
#' @param a1 A numeric vector.
#' @param X A numeric matrix.
#'
#' @return A numeric vector representing the column sums of the element-wise product of "X" and the exponential
#' of the matrix product of "X" and "a1".
#'
#' @examples
#' a1 <- c(1, 2, 3)
#' X <- matrix(1:9, nrow = 3)
#' gradfn(a1, X)
#'
#' @noRd
gradfn <- function(a1, X){
  colSums(sweep(X, 1, exp(X %*% a1), "*"))
}

#' Calculate Effective Sample Size (ESS)
#'
#' This function calculates the Effective Sample Size (ESS) based on the provided weights.
#'
#' @param wt A numeric vector of weights.
#' @return A single numeric value representing the Effective Sample Size (ESS).
#' @examples
#'
#' weights <- c(0.2, 0.5, 0.3, 0.1)
#' ess <- ess_calc(weights)
#' print(ess)
#'
#' @noRd

ess_calc <- function(wt) {
  # ESS
  sum(wt)^2 / sum(wt^2)
}

#' Function to do MAIC
#'
#' @param AB_IPD A data.frame of IPD from the AB trial. Generated by `gen_data()`.
#' @param AC_aggregate A data.frame of aggregate data from the AC trial. Generated
#' by `gen_data()`
#' @param adjust_all A logical value indicating whether to adjust for all effect
#' modifiers. Default is TRUE. If TRUE we adjust by both effect modifiers X1 and
#' X2, if FALSE we only adjust by X1.
#'
#' @return A data.frame of maic results, consisting of maic_log_OR, maic_ESS,
#' maic_se, maic_ci_lower, and maic_ci_upper.
#'
#' @examples
#' # generate data
#' test_data <- gen_data()
#'
#' # do maic
#' maic(test_data$AB_IPD, test_data$AC_aggregate)
#'
#' @export

maic <- function(AB_IPD, AC_aggregate, adjust_all = TRUE, type = c("rescaled_weights", "weights")) {

  type <- match.arg(type)

  tryCatch({
    # Centered EMs
    if(adjust_all) {
    centered_X1 <- sweep(with(AB_IPD, cbind(X1, X1^2)), 2,
                         with(AC_aggregate, c(X1_mean, X1_mean^2 + X1_sd^2)), '-')
    centered_X2 <- sweep(with(AB_IPD, cbind(X2, X2^2)), 2,
                         with(AC_aggregate, c(X2_mean, X2_mean^2 + X2_sd^2)), '-')
    centered_EMs <- cbind(centered_X1, centered_X2)

    # Estimate weights
    opt1 <- optim(par = c(0,0,0,0), fn = objfn, gr = gradfn, X = centered_EMs, method = "BFGS")
    } else {
      centered_EMs <- sweep(with(AB_IPD, cbind(X2, X2^2)), 2,
                             with(AC_aggregate, c(X2_mean, X2_mean^2 + X2_sd^2)), '-')

      # Estimate weights
      opt1 <- optim(par = c(0,0), fn = objfn, gr = gradfn, X = centered_EMs, method = "BFGS")

    }
    a1 <- opt1$par
    wt <- exp(centered_EMs %*% a1)
    rescaled_wt <- (wt / sum(wt)) * nrow(AB_IPD)

    # Binomial GLM
    fit1 <- AB_IPD %>%
      dplyr::mutate(y0 = 1 - y, wt = wt) %>%
      stats::glm(cbind(y, y0) ~ treatment, data = ., family = binomial, weights = wt)

    # Sandwich estimator of variance matrix
    V.sw <- sandwich::vcovHC(fit1)

    # The log OR of B vs. A is just the treatmentB parameter estimate
    d.AB.MAIC.log <- stats::coef(fit1)["treatmentB"]
    var.d.AB.MAIC.log <- V.sw["treatmentB", "treatmentB"]

    # Estimated log OR of C vs. A from the AC trial
    d.AC.log <- with(AC_aggregate, log(y_C_sum * (N_A - y_A_sum) / (y_A_sum * (N_C - y_C_sum))))
    var.d.AC.log <- with(AC_aggregate, 1/y_A_sum + 1/(N_A - y_A_sum) + 1/y_C_sum + 1/(N_C - y_C_sum))

    # Indirect comparison of C vs. B in AC trial
    d.BC.MAIC.log <- d.AC.log - d.AB.MAIC.log
    var.d.BC.MAIC.log <- var.d.AC.log + var.d.AB.MAIC.log

    # Confidence interval
    CI <- ci_from_x_and_se(d.BC.MAIC.log, sqrt(var.d.BC.MAIC.log))

    wt_df <- data.frame(
      unrescaled_weights = wt,
      rescaled_weights = rescaled_wt
    )

    weights <- if (type == "rescaled_weights") {
      wt_df$rescaled_weights
    } else {
      wt_df$unrescaled_weights
    }

    wt_ESS <- ess_calc(weights)
    wt_N <- length(weights)

    # Combine results
    results <- cbind(
      data.frame(
        maic_log_OR = d.BC.MAIC.log,
        maic_se = sqrt(var.d.BC.MAIC.log),
        N = wt_N,
        ESS = wt_ESS,
        ESS_N_ratio = wt_ESS /wt_N * 100,
        Min = min(weights),
        Q1 = stats::quantile(weights, 0.25),
        Median = stats::median(weights),
        Q3 = stats::quantile(weights, 0.75),
        Max = max(weights),
        Mean = mean(weights),
        SD = stats::sd(weights),
        zero_weights = sum(weights < 0.001),
        greater_than_3_weights = sum(weights > 3)
      ),
      CI
    ) %>% dplyr::rename(
      maic_ci_lower = ci_lower,
      maic_ci_upper = ci_upper
    )

    rownames(results) <- NULL
    results
  }, error = function(e) {
    # If an error occurs, return a data frame of NA values
    data.frame(
      maic_log_OR = NA,
      N = NA,
      ESS = NA,
      ESS_N_ratio = NA,
      Min = NA,
      Q1 = NA,
      Median = NA,
      Q3 = NA,
      Max = NA,
      Mean = NA,
      SD = NA,
      zero_weights = NA,
      greater_than_3_weights = NA,
      maic_se     = NA,
      maic_ci_lower = NA,
      maic_ci_upper = NA
    )
  })
}
