#' Function to do STC
#'
#' This function performs simulated treatment comparison (STC).
#'
#' @param AB_IPD A data.frame of IPD from the AB trial. Generated by `gen_data()`.
#' @param AC_aggregate A data.frame of aggregate data from the AC trial. Generated
#' by `gen_data()`
#' @param adjust_all A logical value indicating whether to include all effect
#' modifiers in the regression model. Default is TRUE. If TRUE we include both effect
#' modifiers X1 and X2, if FALSE we only include X1.
#'
#' @return A data.frame of stc results, consisting of stc_log_OR, stc_se, stc_ci_lower,
#' and stc_ci_upper.
#'
#' @examples
#' # generate data
#' test_data <- gen_data()
#'
#' # do stc
#' stc(test_data$AB_IPD, test_data$AC_aggregate)
#'
#' @export
stc <- function(AB_IPD, AC_aggregate, adjust_all = TRUE) {
  AB_IPD$y0 <- 1 - AB_IPD$y  # Add in dummy non-event column

  # Fit binomial GLM
  if (adjust_all) {
  STC.GLM <- stats::glm(
    cbind(y,y0) ~ treatment*I(X1 - AC_aggregate$X1_mean) +
                  treatment*I(X2 - AC_aggregate$X2_mean),
    data = AB_IPD,
    family = binomial)
  } else {
    STC.GLM <- stats::glm(
      cbind(y,y0) ~ treatment*I(X2 - AC_aggregate$X2_mean),
      data = AB_IPD,
      family = binomial)
  }
  # Estimated log OR of B vs. A in the AC trial
  d.AB.STC.log <- stats::coef(STC.GLM)["treatmentB"]
  var.d.AB.STC.log <- stats::vcov(STC.GLM)["treatmentB","treatmentB"]

  # Estimated log OR of C vs. A from the AC trial
  d.AC.log <- with(AC_aggregate, log(y_C_sum * (N_A - y_A_sum) / (y_A_sum * (N_C - y_C_sum))))
  var.d.AC.log <- with(AC_aggregate, 1/y_A_sum + 1/(N_A - y_A_sum) + 1/y_C_sum + 1/(N_C - y_C_sum))

  # Indirect comparison of C vs. B in AC trial
  d.BC.STC.log <- d.AC.log - d.AB.STC.log
  var.d.BC.STC.log <- var.d.AC.log + var.d.AB.STC.log

  # Confidence interval
  CI <- calc_ci(d.BC.STC.log, sqrt(var.d.BC.STC.log))

  # Results
  results <-
    cbind(
      data.frame(
        stc_log_OR = d.BC.STC.log,
        stc_se = sqrt(var.d.BC.STC.log)),
      CI
    ) %>% dplyr::rename(
      stc_ci_lower = ci_lower,
      stc_ci_upper = ci_upper
    )

  rownames(results) <- NULL

  results
}


